import { requireAdminPermission } from '@/lib/admin/server';
import { createPayoutDraftAction, approvePayoutBatchAction, markPayoutItemPaidAction, savePlatformCollectionAccountAction, savePlatformCassoWebhookAction } from './actions';

export default async function AdminPayoutsPage() {
  const { admin } = await requireAdminPermission('billing.manage');
  const [{ data: batches }, { data: payables }, { data: account }, { data: cassoConnection }] = await Promise.all([
    admin.from('payout_batches').select('*').order('batch_date', { ascending: false }).limit(30),
    admin.from('teacher_payables').select('status, net_amount'),
    admin.from('platform_collection_accounts').select('*').eq('is_active', true).maybeSingle(),
    admin.from('platform_casso_connections').select('id').eq('status', 'active').maybeSingle(),
  ]);
  const available = (payables ?? []).filter((p) => p.status === 'available').reduce((s, p) => s + Number(p.net_amount), 0);
  return <main className="space-y-6 p-6 max-w-6xl">
    <div><h1 className="text-2xl font-bold">Đối soát & chi trả Mari</h1><p className="text-muted-foreground">Tự lập bản nháp lúc 17:00 (giờ Việt Nam). Mari chỉ lưu lệnh và chứng từ; admin chuyển tiền thủ công trên KienlongBank.</p></div>
    <section className="rounded-xl border p-4 space-y-3"><h2 className="font-semibold">Tài khoản Mari thu hộ</h2>{account ? <p>{account.bank_name} · {account.account_number} · {account.account_name}</p> : <p className="text-amber-700">Chưa có STK Mari đang hoạt động.</p>}<form action={savePlatformCollectionAccountAction} className="grid gap-2 md:grid-cols-4"><input name="bankName" required placeholder="Ngân hàng (KienlongBank)" className="rounded border px-3 py-2"/><input name="accountNumber" required placeholder="Số tài khoản" className="rounded border px-3 py-2"/><input name="accountName" required placeholder="Chủ tài khoản Mari" className="rounded border px-3 py-2"/><button className="rounded bg-slate-900 px-3 py-2 text-white">Lưu STK thu hộ</button></form><form action={savePlatformCassoWebhookAction} className="flex gap-2"><input name="webhookSecret" required type="password" placeholder="Webhook secret Casso cấp nền tảng" className="min-w-80 rounded border px-3 py-2"/><button className="rounded border px-3 py-2">{cassoConnection ? 'Thay webhook secret' : 'Kết nối webhook Casso'}</button></form><p className="text-xs text-muted-foreground">Chỉ hóa đơn phát hành sau thời điểm bật mới dùng STK này. Secret được mã hóa trước khi lưu.</p></section>
    <section className="rounded-xl border p-4 flex items-center justify-between"><div><p className="font-semibold">Khoản sẵn sàng chi</p><p className="text-2xl font-bold">{available.toLocaleString('vi-VN')} ₫</p></div><form action={createPayoutDraftAction}><button className="rounded-md bg-orange-500 px-4 py-2 text-white">Tạo/xem đợt hôm nay</button></form></section>
    <section className="rounded-xl border overflow-hidden"><table className="w-full text-sm"><thead className="bg-muted"><tr><th className="p-3 text-left">Ngày / cutoff</th><th className="text-left">Tổng</th><th className="text-left">Trạng thái</th><th></th></tr></thead><tbody>{(batches ?? []).map((batch) => <tr className="border-t" key={batch.id}><td className="p-3">{batch.batch_date} · 17:00</td><td>{Number(batch.total_amount).toLocaleString('vi-VN')} ₫ ({batch.item_count} GV)</td><td>{batch.status}</td><td className="p-2 flex gap-2">{batch.status === 'draft' && <form action={approvePayoutBatchAction.bind(null, batch.id)}><button className="rounded border px-3 py-1">Duyệt</button></form>}<a className="rounded border px-3 py-1" href={`/api/admin/payouts/${batch.id}/export`}>Xuất XLSX</a></td></tr>)}</tbody></table></section>
    <PayoutItems batches={batches ?? []} admin={admin} />
  </main>;
}

async function PayoutItems({ batches, admin }: { batches: any[]; admin: any }) {
  const ids = batches.map((batch) => batch.id); if (!ids.length) return null;
  const { data: items } = await admin.from('payout_items').select('*').in('batch_id', ids).order('created_at', { ascending: false });
  return <section className="rounded-xl border overflow-hidden"><h2 className="p-4 font-semibold">Dòng chi & chứng từ</h2><p className="px-4 pb-3 text-sm text-muted-foreground">Tải biên lai/sao kê trước khi chốt. File được băm SHA-256 và chỉ admin có quyền tải lại.</p><table className="w-full text-sm"><thead className="bg-muted"><tr><th className="p-3 text-left">STK snapshot</th><th className="text-left">Số tiền</th><th className="text-left">Trạng thái</th><th></th></tr></thead><tbody>{(items ?? []).map((item: any) => <tr className="border-t" key={item.id}><td className="p-3">{item.bank_name_snapshot} · {item.account_number_snapshot}<br />{item.account_name_snapshot}</td><td>{Number(item.amount).toLocaleString('vi-VN')} ₫</td><td>{item.status}</td><td className="p-2 space-y-2">{item.status === 'pending' && <><form action="/api/admin/payouts/evidence" method="post" encType="multipart/form-data" className="flex gap-1"><input type="hidden" name="batchId" value={item.batch_id}/><input type="hidden" name="payoutItemId" value={item.id}/><input type="hidden" name="evidenceType" value="bank_receipt"/><input name="file" required type="file" accept="application/pdf,image/*" className="w-44 text-xs"/><button className="rounded border px-2">Tải chứng từ</button></form><form action={async (formData) => { 'use server'; await markPayoutItemPaidAction(item.id, String(formData.get('reference') ?? '')); }} className="flex gap-2"><input name="reference" required placeholder="Mã giao dịch" className="w-36 rounded border px-2"/><button className="rounded border px-2">Đã chi</button></form></>}</td></tr>)}</tbody></table></section>;
}
