import { Badge } from '@/components/ui/badge';

type ReportSession = { date: string; startTime?: string; endTime?: string; learningContent?: string; exercises?: Array<{ title: string; score?: number | null }>; rating?: string; feedback?: string; attendanceStatus: string; attendanceNote?: string };
const attendanceLabel: Record<string, string> = { present: 'Có mặt', late: 'Đi trễ', absent: 'Vắng', excused: 'Có phép', not_marked: 'Chưa điểm danh' };
const attendanceStyle: Record<string, string> = { present: 'border-emerald-200 bg-emerald-50 text-emerald-700', late: 'border-amber-200 bg-amber-50 text-amber-700', absent: 'border-rose-200 bg-rose-50 text-rose-700', excused: 'border-violet-200 bg-violet-50 text-violet-700', not_marked: 'border-zinc-200 bg-zinc-50 text-zinc-600' };
const ratingLabel: Record<string, string> = { EXCELLENT: 'Xuất sắc', GOOD: 'Tốt', AVERAGE: 'Cần cố gắng', POOR: 'Chưa tập trung' };

export function LearningReportTable({ sessions }: { sessions: ReportSession[] }) {
  const badge = (status: string) => <Badge variant="outline" className={`max-w-full whitespace-nowrap px-1.5 text-[10px] ${attendanceStyle[status] || attendanceStyle.not_marked}`}>{attendanceLabel[status] || 'Chưa điểm danh'}</Badge>;
  return <div className="learning-report-table-v2">
    <div className="hidden overflow-hidden rounded-xl border border-orange-200 md:block print:block">
      <table className="w-full table-fixed text-xs">
        <colgroup><col className="w-[6%]" /><col className="w-[10%]" /><col className="w-[32%]" /><col className="w-[12%]" /><col className="w-[8%]" /><col className="w-[15%]" /><col className="w-[10%]" /><col className="w-[7%]" /></colgroup>
        <thead className="bg-orange-500 text-white"><tr>{['STT', 'Ngày', 'Nội dung', 'BTVN', 'Ý thức', 'Nhận xét', 'Chuyên cần', 'Ghi chú'].map((label) => <th key={label} className="h-10 break-words px-1 text-center text-[11px] font-bold">{label}</th>)}</tr></thead>
        <tbody>{sessions.map((session, index) => <tr key={`${session.date}-${index}`} className="align-top border-t border-orange-100 even:bg-orange-50/70"><td className="break-words px-1.5 py-2.5 text-center font-semibold">Buổi {index + 1}</td><td className="px-1.5 py-2.5 text-[11px]"><b>{new Date(`${session.date}T00:00:00`).toLocaleDateString('vi-VN')}</b><br />{session.startTime?.slice(0, 5)}–{session.endTime?.slice(0, 5)}</td><td className="whitespace-nowrap px-2 py-2.5">{session.learningContent || 'Chưa cập nhật nội dung.'}</td><td className="break-words px-1.5 py-2.5">{session.exercises?.length ? session.exercises.map((exercise) => <p key={exercise.title}>• {exercise.title}{exercise.score !== null && exercise.score !== undefined ? <b className="ml-1 text-emerald-700">({exercise.score}/10)</b> : <span className="ml-1 text-zinc-400">(chưa chấm)</span>}</p>) : '—'}</td><td className="break-words px-1.5 py-2.5 text-center">{session.rating ? ratingLabel[session.rating] || session.rating : '—'}</td><td className="break-words whitespace-pre-line px-1.5 py-2.5">{session.feedback || 'Chưa có nhận xét.'}</td><td className="px-1 py-2.5 text-center">{badge(session.attendanceStatus)}</td><td className="break-words whitespace-pre-line px-1.5 py-2.5 text-zinc-600">{session.attendanceNote || '—'}</td></tr>)}</tbody>
      </table>
    </div>
    <div className="space-y-3 md:hidden print:hidden">{sessions.map((session, index) => <details key={`${session.date}-${index}`} className="rounded-xl border border-orange-100 p-4" open={index === 0}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-3"><span className="font-semibold">Buổi {index + 1} · {new Date(`${session.date}T00:00:00`).toLocaleDateString('vi-VN')}</span>{badge(session.attendanceStatus)}</summary><div className="mt-3 space-y-3 border-t pt-3 text-sm leading-6 text-zinc-600"><p><b className="text-zinc-900">Nội dung:</b> {session.learningContent || 'Chưa cập nhật nội dung buổi học.'}</p><p><b className="text-zinc-900">Bài tập:</b> {session.exercises?.length ? session.exercises.map((exercise) => `${exercise.title}${exercise.score !== null && exercise.score !== undefined ? ` (${exercise.score}/10)` : ' (chưa chấm)'}`).join(', ') : 'Chưa giao bài tập.'}</p><p><b className="text-zinc-900">Đánh giá:</b> {session.rating ? ratingLabel[session.rating] || session.rating : 'Chưa đánh giá'}{session.feedback ? ` — ${session.feedback}` : ''}</p><p><b className="text-zinc-900">Ghi chú:</b> {session.attendanceNote || '—'}</p></div></details>)}</div>
  </div>;
}
